version: "3.9"
services:
  # mysql-server-user:
  #   command: --default-authentication-plugin=mysql_native_password
  #   image: "mysql"
  #   volumes:
  #     - ../user-service/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  #   restart: on-failure
  #   environment:
  #     - MYSQL_ROOT_HOST=172.17.0.1
  #     - MYSQL_ROOT_PASSWORD=1
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=user
  #   ports:
  #     - "3307:3306"
  #   restart: always
  # mysql-server-order:
  #   command: --default-authentication-plugin=mysql_native_password
  #   image: "mysql"
  #   volumes:
  #     - ../order-service/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  #   restart: on-failure
  #   environment:
  #     - MYSQL_ROOT_HOST=172.17.0.1
  #     - MYSQL_ROOT_PASSWORD=1
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=order
  #   ports:
  #     - "3308:3306"
  #   restart: always
  # mongo-server-inventory:
  #   image: mongo
  #   volumes:
  #     - ../inventory-service/db/seed.js:/docker-entrypoint-initdb.d/seed.js
  #   environment:
  #     - MONGO_INITDB_DATABASE=inventory
  #   ports:
  #     - 3309:27017
  #   restart: always

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   restart: always
  gateway-server:
    build:
      dockerfile: ../gateway/Dockerfile
      context: ../gateway
    environment:
      GATEWAY_PORT: "9000"
      USER_SERVICE_PORT: "4447"
      ORDER_SERVICE_PORT: "4448"
      INVENTORY_SERVICE_PORT: "4449"
      USER_MYSQL_URL: "127.0.0.1:3307"
      ORDER_MYSQL_URL: "127.0.0.1:3308"
      INVENTORY_MYSQL_URL: "127.0.0.1:3309"
    network_mode: host
    restart: always
  # order-server:
  #   build:
  #     dockerfile: ../order-service/Dockerfile
  #     context: ../order-service
  #   environment:
  #     GATEWAY_PORT : "9000"
  #     USER_SERVICE_PORT : "4447"
  #     ORDER_SERVICE_PORT : "4448"
  #     INVENTORY_SERVICE_PORT : "4449"
  #     USER_MYSQL_URL : "127.0.0.1:3307"
  #     ORDER_MYSQL_URL : "127.0.0.1:3308"
  #     INVENTORY_MYSQL_URL : "127.0.0.1:3309"
  #   network_mode: host
  #   restart: always
  # user-server:
  #   build:
  #     dockerfile: ../user-service/Dockerfile
  #     context: ../user-service
  #   environment:
  #     GATEWAY_PORT : "9000"
  #     USER_SERVICE_PORT : "4447"
  #     ORDER_SERVICE_PORT : "4448"
  #     INVENTORY_SERVICE_PORT : "4449"
  #     USER_MYSQL_URL : "127.0.0.1:3307"
  #     ORDER_MYSQL_URL : "127.0.0.1:3308"
  #     INVENTORY_MYSQL_URL : "127.0.0.1:3309"
  #   network_mode: host
  #   restart: always
  # inventory-server:
  #   build:
  #     dockerfile: ../inventory-service/Dockerfile
  #     context: ../inventory-service
  #   environment:
  #     GATEWAY_PORT : "9000"
  #     USER_SERVICE_PORT : "4447"
  #     ORDER_SERVICE_PORT : "4448"
  #     INVENTORY_SERVICE_PORT : "4449"
  #     USER_MYSQL_URL : "127.0.0.1:3307"
  #     ORDER_MYSQL_URL : "127.0.0.1:3308"
  #     INVENTORY_MYSQL_URL : "127.0.0.1:3309"
  #   network_mode: host
  #   restart: always
