// AUTO_DEBIT
select * from AUTO_DEBIT_REGISTER  where reference_1 like'PE06000021738';
select * from AUTO_DEBIT_REGISTER;
select * from AUTO_DEBIT_CONFIG;

SELECT * FROM AUTO_DEBIT_CONFIG_GROUP_SERVICE;

SELECT * FROM AUTO_DEBIT_PAYMENT_TRACKING_DATA;

SELECT * FROM BILL_AVAILABLE;

SELECT ID, CODE, NAME, PARENTID, STATUS, STATUSBACKEND, REDIRECTTO, HOST, PORT, URI FROM SERVICE WHERE parentID =4 ;

// BILL REMINDER
SELECT * FROM REMINDER_CONFIG;

SELECT * FROM BILL;

SELECT count(*) FROM TELCO_REMIND;

SELECT * FROM BILL_AVAILABLE ;

SELECT * FROM BILL_AVAILABLE where LAST_SYNC_bill > '1-JUN-22' AND STATUS = 1;

SELECT * FROM BILL_CACHE WHERE SERVICECODE like 'evn_hcm' and lastupdate > '1-JUN-22 5.01.37.000000000 PM'
bill_id in ();

SELECT * FROM BILL_CACHE ;

