// Code generated by goctl. DO NOT EDIT.
package types

type Product struct {
	ID       string            `json:"_id"`
	Name     string            `json:"name"`
	Quantity int               `json:"quantity"`
	Data     map[string]string `json:"data"`
}
