// Code generated by goctl. DO NOT EDIT.
package types

type TestGetReq struct {
	Token string `form:"token"`
}

type TestGetResp struct {
	Success bool `json:"success"`
}

type OrderReq struct {
	Token    string    `json:"token"`
	Products []Product `json:"products"`
}

type Product struct {
	ID       string            `json:"_id"`
	Name     string            `json:"name"`
	Quantity int               `json:"quantity"`
	Data     map[string]string `json:"data"`
}

type OrderResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func BuildBaseResponse(success bool) *OrderResp {
	response := &OrderResp{
		Success: false,
		Message: "Create order fail",
	}
	if success {
		response.Success = true
		response.Message = "Create order successfully"
	}
	return response
}
