version: "3.9"
services:
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    environment:
      - cluster.name=elastic-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    mem_limit: 1g
    restart: always
    ports: 
      - 9200:9200

  elasticsearch-seed:
    container_name: elasticsearch-seed
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch2:9200
      - INDEX_NAME=courses
    volumes:
      - ./index-bulk-payload.json:/seed/index-bulk-payload.json
