// Code generated by goctl. DO NOT EDIT!
// Source: userService.proto

package server

import (
	"context"

	"orderProduct/rpc/userService/internal/logic"
	"orderProduct/rpc/userService/internal/svc"
	"orderProduct/rpc/userService/userservice"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) VerifyUserByToken(ctx context.Context, in *userservice.TokenRequest) (*userservice.BaseRespond, error) {
	l := logic.NewVerifyUserByTokenLogic(ctx, s.svcCtx)
	return l.VerifyUserByToken(in)
}
